export const FETCH_ALBUMS = "FETCH_ALBUMS";
export const FETCH_ALBUM_DETAIL = "FETCH_ALBUM_DETAIL";
export const ADD_ALBUM = "ADD_ALBUM";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
