export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';



